export { apiRoutePatterns, apiRoutes, appRoutes } from './routes'
export {
	activeRecallGradeRequestSchema,
	activeRecallGradeResponseSchema,
	activeRecallModeSchema,
	activeRecallRegionSchema,
	activeRecallStepStatusSchema,
	activeRecallVerdictSchema,
} from './activeRecall'
export type {
	ActiveRecallGradeRequest,
	ActiveRecallGradeResponse,
	ActiveRecallRegion,
	ActiveRecallVerdict,
} from './activeRecall'
export {
	agentActionCreateSchema,
	agentActionSummarySchema,
	agentActionUndoPayloadSchema,
	agentActionUndoResultSchema,
	canvasRecordSchema,
} from './agentActions'
export type {
	AgentActionCreate,
	AgentActionSummary,
	AgentActionUndoPayload,
	CanvasRecordSnapshot,
} from './agentActions'
export {
	MAX_OFFICE_BYTES,
	MAX_PDF_BYTES,
	MAX_PDF_PAGE_IMAGE_BYTES,
	MAX_PDF_PAGES,
	documentErrorCodeSchema,
	documentPageSummarySchema,
	documentStatusResponseSchema,
	documentStatusSchema,
	documentSummarySchema,
	pdfTextBlockSchema,
	pdfTextLayoutSchema,
} from './documents'
export {
	examPlanInputSchema,
	examPlanSchema,
	examPracticeSetSchema,
	quizArtifactPayloadSchema,
	registerStudyArtifactsSchema,
	studyArtifactInputSchema,
	studyArtifactKindSchema,
} from './exams'
export { globalSearchQuerySchema, globalSearchResultSchema } from './search'
export type {
	GlobalSearchDocumentResult,
	GlobalSearchLectureResult,
	GlobalSearchResult,
	GlobalSearchShapeResult,
} from './search'
export {
	MAX_AUDIO_BYTES,
	lectureSegmentSchema,
	lectureSchema,
	lectureStatusSchema,
	lectureSummarySchema,
} from './lectures'
export type {
	Lecture,
	LectureSegment,
	LectureStatus,
	LectureSummary,
} from './lectures'
export type {
	ExamDeckStatus,
	ExamPattern,
	ExamPlan,
	ExamPlanInput,
	ExamPracticeSet,
	ExamStudyTask,
	StudyArtifactInput,
	StudyArtifactKind,
} from './exams'
export type {
	DocumentErrorCode,
	DocumentErrorResponse,
	DocumentPageSummary,
	DocumentStatus,
	DocumentStatusResponse,
	DocumentSummary,
	PDFTextBlock,
} from './documents'
export {
	CRAFT_WHITEBOARD_CONFLICT_MESSAGE,
	CRAFT_DOCUMENT_SHAPE_TYPE,
	MAX_CRAFT_APPEND_MARKDOWN_LENGTH,
	MAX_CRAFT_BLOCK_UPDATES,
	MAX_CRAFT_DOCUMENT_LINKS,
	MAX_CRAFT_WHITEBOARD_ELEMENTS,
	craftAPIRoutes,
	craftConnectionInputSchema,
	craftConnectionStatusSchema,
	craftDocumentAppendInputSchema,
	craftDocumentAppendOutputSchema,
	craftDocumentBlocksUpdateInputSchema,
	craftDocumentBlocksUpdateOutputSchema,
	craftDocumentCandidateSchema,
	craftDocumentLinkInputSchema,
	craftDocumentLinkSchema,
	craftDocumentPreviewSchema,
	craftDocumentShapeProps,
	craftDocumentShapeValidator,
	craftShapeSchemas,
	craftWhiteboardSaveInputSchema,
	craftWhiteboardCandidateSchema,
	craftWhiteboardImportSchema,
	craftWhiteboardRecordSchema,
	craftWhiteboardSaveOutputSchema,
	createCraftWhiteboardRevision,
	getCraftDocumentCitationHref,
	parseCraftDocumentCitationHref,
} from './craft'
export type {
	CraftConnectionStatus,
	CraftDocumentAppendInput,
	CraftDocumentAppendOutput,
	CraftDocumentBlockUpdate,
	CraftDocumentBlocksUpdateInput,
	CraftDocumentBlocksUpdateOutput,
	CraftDocumentCandidate,
	CraftDocumentLink,
	CraftDocumentPreview,
	CraftDocumentShapeProps,
	CraftJSONValue,
	CraftWhiteboardCandidate,
	CraftWhiteboardElement,
	CraftWhiteboardImport,
	CraftWhiteboardRecord,
	CraftWhiteboardSaveOutput,
} from './craft'
export {
	MAX_CANVAS_SELECTION_IMAGE_DATA_LENGTH,
	canvasAnchorSchema,
	canvasContextSchema,
	canvasSelectionImageSchema,
	canvasShapeRelationshipSchema,
	canvasShapeSchema,
	canvasShapeTextSchema,
	canvasContextShapeStyleSchema,
	canvasPDFPageRegionSchema,
	canvasPDFTextSelectionSchema,
	canvasDocumentTextSchema,
} from './canvasContext'
export type {
	CanvasAnchor,
	CanvasContext,
	CanvasSelectionImage,
	CanvasShape,
	CanvasShapeRelationship,
	CanvasShapeText,
	CanvasContextShapeStyle,
	CanvasPDFPageRegion,
	CanvasPDFTextSelection,
	CanvasDocumentText,
} from './canvasContext'
export {
	CANVAS_CUSTOM_COLOR_NAMES,
	registerCanvasCustomColors,
} from './canvasColors'
export type { CanvasCustomColor } from './canvasColors'
export {
	CANVAS_PLAN_VERSION,
	MAX_CANVAS_PLAN_CONNECTORS,
	MAX_CANVAS_PLAN_ELEMENTS,
	canvasColorSchema,
	canvasConnectorSchema,
	canvasContainerSchema,
	canvasEditSchema,
	canvasLayerSchema,
	canvasLayoutSchema,
	canvasObjectReferenceSchema,
	canvasPlacementSchema,
	canvasPlanElementSchema,
	canvasPlanIDSchema,
	canvasPlanInputSchema,
	canvasPlanSchema,
	normalizeCanvasPlanInput,
	canvasShapeStyleSchema,
	canvasSizeSchema,
	canvasSpacingSchema,
	canvasSpacingTokenSchema,
} from './canvasPlan'
export type {
	CanvasColor,
	CanvasConnector,
	CanvasContainer,
	CanvasEdit,
	CanvasLayer,
	CanvasLayout,
	CanvasObjectReference,
	CanvasPlacement,
	CanvasPlan,
	CanvasPlanInput,
	CanvasPlanElement,
	CanvasShapeStyle,
	CanvasSize,
	CanvasSpacing,
} from './canvasPlan'
export {
	FLASHCARD_CANVAS_HEIGHT,
	FLASHCARD_CANVAS_WIDTH,
	FLASHCARD_SHAPE_TYPE,
	CONCEPT_MAP_SHAPE_TYPE,
	QUIZ_SHAPE_TYPE,
	REVIEW_SHAPE_TYPE,
	WALKTHROUGH_SHAPE_TYPE,
	MATH_SHAPE_TYPE,
	PDF_PAGE_SHAPE_TYPE,
	TEACH_BACK_SHAPE_TYPE,
	LECTURE_SHAPE_TYPE,
	conceptMapProposalSchema,
	conceptMapShapeProps,
	conceptMapShapeValidator,
	flashcardProposalSchema,
	flashcardShapeMigrations,
	flashcardShapeProps,
	flashcardShapeValidator,
	quizProposalSchema,
	quizShapeProps,
	quizShapeValidator,
	MAX_EQUATION_LINES,
	equationProposalSchema,
	mathShapeProps,
	mathShapeValidator,
	normalizeEquationLatex,
	practiceSetProposalSchema,
	pdfSourceReferenceSchema,
	reviewProposalSchema,
	reviewShapeProps,
	reviewShapeValidator,
	studyPackProposalSchema,
	studyShapeSchemas,
	walkthroughProposalSchema,
	walkthroughShapeProps,
	walkthroughShapeValidator,
	pdfPageShapeMigrations,
	pdfPageShapeProps,
	pdfPageShapeValidator,
	teachBackShapeProps,
	teachBackShapeValidator,
	lectureShapeProps,
	lectureShapeValidator,
} from './studyShapes'
export type {
	ConceptMapProposal,
	ConceptMapShapeProps,
	EquationProposal,
	FlashcardProposal,
	FlashcardShapeProps,
	MathShapeProps,
	PracticeSetProposal,
	PDFSourceReference,
	QuizProposal,
	QuizShapeProps,
	ReviewProposal,
	StudyPackProposal,
	ReviewShapeProps,
	WalkthroughProposal,
	WalkthroughShapeProps,
	PDFPageShapeProps,
	TeachBackShapeProps,
	LectureShapeProps,
} from './studyShapes'
export { boardSchema, publicConfigSchema, studyConversationSchema } from './types'
export type { Board, PublicConfig, StudyConversation } from './types'
export {
	boardCourseUpdateSchema,
	boardRoleSchema,
	courseInputSchema,
	courseSchema,
	courseUpdateSchema,
	invitationRoleSchema,
	spaceInvitationInputSchema,
	spaceInvitationCreatedSchema,
	spaceInvitationPreviewSchema,
	spaceInvitationSchema,
	spaceMemberSchema,
	spaceMemberRoleUpdateSchema,
} from './workspace'
export type {
	BoardRole,
	Course,
	InvitationRole,
	SpaceInvitation,
	SpaceInvitationCreated,
	SpaceInvitationPreview,
	SpaceMember,
} from './workspace'
export {
	SPOTIFY_SCOPES,
	spotifyAgentPlayInputSchema,
	spotifyAgentPlayOutputSchema,
	spotifyPlaybackActionSchema,
	spotifyPlaybackItemSchema,
	spotifyPlaybackSchema,
	spotifyPlayerResponseSchema,
} from './spotify'
export type {
	SpotifyAgentPlayInput,
	SpotifyAgentPlayOutput,
	SpotifyPlayback,
	SpotifyPlaybackAction,
	SpotifyPlaybackItem,
	SpotifyPlayerResponse,
} from './spotify'
export {
	DEFAULT_STUDY_MODEL,
	DEFAULT_STUDY_MODEL_MODE,
	DEFAULT_STUDY_REASONING_EFFORT,
	STUDY_CONTEXT_WINDOW_TOKENS,
	STUDY_MODELS,
	STUDY_REASONING_EFFORTS,
	getStudyModel,
	getStudyContextLectureSources,
	studyModelModeSchema,
	studyModelSupportsReasoning,
	studyReasoningEffortSchema,
} from './studyChat'
export type {
	StudyContextReceipt,
	StudyMessageContextChip,
	StudyMessageMetadata,
	StudyModelMode,
	StudyReasoningEffort,
} from './studyChat'
export {
	DEFAULT_AGENT_PROFILE,
	agentMemorySchema,
	agentMemoryKeySchema,
	agentMemoryKindSchema,
	agentMemoryProposalSchema,
	agentPersonalitySchema,
	agentProfileSchema,
	agentPromptSourcesSchema,
	flashcardReviewRatingSchema,
	dueFlashcardSchema,
	flashcardAnswerAttemptSchema,
	flashcardAnswerAttemptResultSchema,
	flashcardAnswerAttemptRequestSchema,
	flashcardAnswerCompletionResultSchema,
	flashcardAnswerCompletionSchema,
	flashcardAnswerVerdictSchema,
	flashcardFinalVerdictSchema,
	flashcardGradingMethodSchema,
	manualAgentMemorySchema,
	mistakeProposalSchema,
	registerFlashcardsSchema,
	studyModeSchema,
	studyTodayDashboardSchema,
} from './studyLearning'
export type {
	AgentMemory,
	AgentMemoryKind,
	AgentMemoryProposal,
	AgentPersonality,
	AgentProfile,
	AgentPromptSources,
	DueFlashcard,
	FlashcardAnswerAttempt,
	FlashcardAnswerAttemptResult,
	FlashcardAnswerCompletionResult,
	FlashcardAnswerAttemptRequest,
	FlashcardAnswerCompletion,
	FlashcardAnswerVerdict,
	FlashcardFinalVerdict,
	FlashcardGradingMethod,
	FlashcardReviewRating,
	ManualAgentMemory,
	MistakeProposal,
	StudyMistake,
	StudyMode,
	StudyTodayDashboard,
	StudyTodayPattern,
	StudyTodayTrendDay,
} from './studyLearning'
export {
	DEFAULT_LOCK_IN_REVIEW_INTERVAL_SECONDS,
	LOCK_IN_REVIEW_INTERVAL_OPTIONS,
	MAX_LOCK_IN_IMAGE_DATA_LENGTH,
	lockInReviewImageSchema,
	lockInReviewRequestSchema,
	lockInReviewResponseSchema,
	lockInReviewStatusSchema,
} from './lockIn'
export type {
	LockInReviewImage,
	LockInReviewRequest,
	LockInReviewResponse,
	LockInReviewStatus,
} from './lockIn'
